const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Plugins.video,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.JavaScriptInEvents.EventosSplash_Event3,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.Every
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{Chao: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Plataforma: 0},
	{Player1: 0},
	{Teclado: 0},
	{Vídeo: 0},
	{Telaselecao: 0},
	{Mouse: 0},
	{Player2Select: 0},
	{Player1Select: 0},
	{displayGojo: 0},
	{displaySukuna: 0},
	{GOJODOMAIN: 0},
	{DominioSukuna: 0},
	{barreira: 0},
	{SUKUNADOMAIN: 0},
	{Projétil: 0},
	{DestruirExternamente: 0},
	{AKA: 0},
	{AO: 0},
	{BotaoSkip: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Player2: 0},
	{KIYOSHIKIMURASAKI: 0},
	{Cleave: 0},
	{Dismantle: 0},
	{BARRA: 0},
	{vidap2: 0},
	{Vidap1: 0},
	{NomeP2: 0},
	{NomeP1: 0},
	{Kai: 0},
	{Áudio: 0},
	{p1escolheu: 0},
	{p1selecionouquem: 0},
	{p2selecionouquem: 0},
	{totalcliques: 0},
	{acaop1: 0},
	{acaop2: 0},
	{vidasp1: 0},
	{vidasp2: 0},
	{p1golpeado: 0},
	{p2golpeado: 0},
	{Cooldownp1: 0},
	{Cooldownp2: 0},
	{CDFísicop1: 0},
	{CDFísicop2: 0}
];

self.InstanceType = {
	Chao: class extends self.ITiledBackgroundInstance {},
	Player1: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Vídeo: class extends self.IWorldInstance {},
	Telaselecao: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Player2Select: class extends self.ISpriteInstance {},
	Player1Select: class extends self.ISpriteInstance {},
	displayGojo: class extends self.ISpriteInstance {},
	displaySukuna: class extends self.ISpriteInstance {},
	GOJODOMAIN: class extends self.ISpriteInstance {},
	DominioSukuna: class extends self.ITiledBackgroundInstance {},
	barreira: class extends self.ISpriteInstance {},
	SUKUNADOMAIN: class extends self.ISpriteInstance {},
	AKA: class extends self.ISpriteInstance {},
	AO: class extends self.ISpriteInstance {},
	BotaoSkip: class extends self.ISpriteFontInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Player2: class extends self.ISpriteInstance {},
	KIYOSHIKIMURASAKI: class extends self.ISpriteInstance {},
	Cleave: class extends self.ISpriteInstance {},
	Dismantle: class extends self.ISpriteInstance {},
	BARRA: class extends self.ISpriteInstance {},
	vidap2: class extends self.ISpriteInstance {},
	Vidap1: class extends self.ISpriteInstance {},
	NomeP2: class extends self.ISpriteInstance {},
	NomeP1: class extends self.ISpriteInstance {},
	Kai: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {}
}